package com.safarov.tech_app.dto.response;


public enum StatusCode {
    SUCCESS,
    CBAR_ERROR,
    INVALID_DTO,
    ALREADY_EXIST,
    USER_NOT_EXIST,
    INVALID_AMOUNT,
    EQUALS_ACCOUNT,
    INTERNAL_ERROR,
    BAD_CREDENTIALS,
    ACCOUNT_NOT_EXIST,
    EQUALS_ACCOUNT_NO,
    NOT_ACTIVE_ACCOUNT,
    INSUFFICIENT_BALANCE,
    ACCOUNT_ACCESS_FORBIDDEN

}
