package com.safarov.tech_app.dto.response;


public enum StatusCode {
    SUCCESS,
    INVALID_DTO,
    ALREADY_EXIST,
    USER_NOT_EXIST,
    INVALID_AMOUNT,
    EQUALS_ACCOUNT,
    INTERNAL_ERROR,
    BAD_CREDENTIALS,
    ACCOUNT_NOT_EXIST,
    NOT_ACTIVE_ACCOUNT,
    ACCOUNT_ACCESS_FORBIDDEN, INSUFFICIENT_BALANCE

}
